### ISSUE TITLE
Get data into challenges plugin

### ISSUE THREAD

**Issue by JMurphyWeb** [postgres-plugin/challenges#10]
Using Marie's script, populate db associated with this plugin with mock data.

**Comment by JMurphyWeb** [comment]
Estimate: 1hr

**Comment by JMurphyWeb** [comment]
Config needed sorting out as we don't have configs in the same way as the real application.

Now it is complaining that the tags table doesn't exist....

**Comment by nelsonic** [comment]
@JMurphyWeb this is not a very _descriptive_ user/technical story... `Why?` do we need to do this?

**Comment by JMurphyWeb** [comment]
having 3 repositories on the go is getting confusing. If we can add uniform data to each of our plugins database, it will mean there is one less blocker when writing tests for our new queries.

I do not want to worry about checking which tables i have already set up, and what data is in those tables before thinking about writing a query.

**Comment by nelsonic** [comment]
@JMurphyWeb while I _agree_ that _working_ on multiple repositories (_and having to publish an NPM package each time we want to update the version of the plugin being used in one of the repos_) can be _tedious_ I _understand_ why it was done that way. 

My _personal_ preference is that we only split out a piece of functionality into a _separate_ repository when it is:
+ A logically independent/separate/decoupled unit of functionality 
+ A micro-service that performs a specific task and has an well-documented API which is "_consumed_" by the "_main_" application.
+ A clearly re-useable component that can be made _generic_ and open source (_which other people can use in their projects_).
+ A unit of code that is "_difficult_" or _particularly **slow**_ to test e.g. `email` or `auth`.

In the case of the EMF application I _feel_ that the Tags is a _good_ candidate for a unit which can be made into a _separate_ plugin. I don't think it needs to be in a separate organisation. 
For example in "TC" we have _several_ destinct repos which form the "Tagging System": https://github.com/numo-labs/?utf8=%E2%9C%93&q=tagg but in EMF we _litterally_ just need a _tiny_ plugin to perform this functionality.

**Comment by JMurphyWeb** [comment]
This issue was only created because I wanted to input realistic and meaningful  mock data into our plugins to help reduce confusion. 

I think there is a discussion to be had on how useful a challenges and people plugin really is. I will be sure to copy your comment over if I get round to making that issue today.
