### ISSUE TITLE
Replace import mock data with 

### ISSUE THREAD

**Issue by SimonLab** [postgres-plugin/challenges#22]
The [import Mock data file](https://github.com/postgres-plugin/challenges/blob/master/fixtures/importMockData.js) create all tables with all data. To simplify the tests and how to import only the data linked to the challenge module we need to replicate the logic of the [people plugin](https://github.com/postgres-plugin/people/blob/master/lib/helpers/initialise-query.js)

**Comment by JMurphyWeb** [comment]
Almost there, tests need fixing.
