### ISSUE TITLE
checkEditable will return true for secondary user

### ISSUE THREAD

**Issue by SimonLab** [postgres-plugin/challenges#63]
[checkEditable query](https://github.com/postgres-plugin/challenges/blob/master/lib/queries/checkEditable.js) will return true for any type of user belonging to the organisation where the challenge is linked to.
Do we want to only return true for primary user instead?

**Comment by mk4111** [comment]
Hi @SimonLab - yes I think we need to add a check for `usertype = primary` in our query, and that this should be enough for most cases.

If we do limit this to checking primary users only, we will need to figure out how we are going to checkEditable for secondary users when they want to edit their own profile

**Comment by JMurphyWeb** [comment]
We can (and do in most places) check whether the user is a primary/admin in the handler.  That is why I left it out.

**Comment by JMurphyWeb** [comment]
Can't think of a reason not to put this logic into the query though

**Comment by SimonLab** [comment]
@mk4111 yes added usertype = primary will be good. The checkEditable function for challenges is not link to the people profile.

**Comment by SimonLab** [comment]
resolved with #64
